Pull Request for sam1123
LiterateProgramming/exploring-github pull request #11
Opened 2022-02-28 21:15 UTC by sammcdsam

Pull Request for the assignment intro to github. 
Included are my files from the intro to sphinx assignment as well as my partners code.

2022-03-02 21:14 UTC, bjones1 commented
Delete all the files in `_build` and rebase/merge with the latest commits in master.

2022-03-02 21:19 UTC, bjones1 requested changes

2022-03-02 21:19 UTC, bjones1 commented on sam1123/.gitignore
> +# ignore codechat_config.yaml and conf.py
Good idea, but not needed here -- delete this file.

2022-03-02 21:19 UTC, bjones1 commented on sam1123/_build/_sources/index.rs
> +
Delete this file.

2022-03-02 21:19 UTC, bjones1 commented on sam1123/feedback.rst
> +********
Delete this file.

2022-03-02 21:19 UTC, bjones1 commented on sam1123/index.rst
> +.. template documentation master file, created by
Delete this file.

2022-03-02 21:19 UTC, bjones1 commented on sam1123/shadows_of_knight_ep1.py
> +# ***************************
This is your partner's code, correct? If so, delete it.

2022-03-02 21:20 UTC, bjones1 commented
Sam, this is a good start. Respond to my comment by midnight on 3-Mar.

2022-03-07 23:58 UTC, bjones1 commented
I haven't seen any progress on this...

2022-03-08 02:17 UTC, sammcdsam commented
Sorry Dr. Jones I didnt realize you wanted me to reply here on Thursday. I was working on a presentation on a different class and thought I could just squeeze this in before the morning.

2022-03-08 16:47 UTC, bjones1 requested changes

2022-03-08 16:47 UTC, bjones1 commented on sam1123/sam1123_codechat_intro.py
> +#
Remove notes and integrate their suggestions into your code.

2022-03-08 16:47 UTC, bjones1 commented on sam1123/sam1123_codechat_intro.py
> +# .. note::
Remove / integrate.

2022-03-08 16:47 UTC, bjones1 commented on sam1123/sam1123_codechat_intro.py
> +# n: the total number of nodes in the level, including the gateways
Use a bulleted list of a definition list:

```
# :l: the number of links
# :e: the number of exit gateways
```

2022-03-08 16:48 UTC, bjones1 commented
It looks like a lot of the notes I left in the previous assignment haven't been addressed -- make sure to improve your code based on that feedback, then I can provide more review.

2022-03-10 19:57 UTC, bjones1 commented
Still waiting on these changes...

2022-03-18 23:17 UTC, bjones1 commented
It looks like there's one more section of notes you haven't edited combined, but everything else looks fine. See https://github.com/LiterateProgramming/exploring-github/pull/11/files#diff-afd97f031b3bbad2bf8c611611d502d73d47d0d960cf088c272dbea5df432f91R6.

2022-03-24 21:59 UTC, bjones1 commented
Ping...still waiting on this...

2022-03-25 16:42 UTC, bjones1 commented
I see some progress, but still unresolved problems. Comment here when your code is ready for review.

2022-03-25 16:42 UTC, bjones1 commented
Or message me for more details on what I'd like to see.

2022-04-20 15:52 UTC, merged