Final Changes with Dr. J notes
LiterateProgramming/exploring-github pull request #22
Opened 2022-03-04 06:53 UTC by Kahjax

2022-03-04 14:58 UTC, bjones1 requested changes

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +/* This while statement is the beginning of the beginning of the game loop and it allows causes all of your test cases to run
Make this a `//` comment and indent it to align with the `while` statement.

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +*/
Combine these two comments -- there's no reason to end one then just begin another.

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +*/
Combine comments

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +        /* In this case the light of power at the X and Y coordinates are greater than Thor's initial condition so 2 if condition statements have to be implemented. Thor's initial X and Y conditions
Use `//` for single-line comments, here and throughout the file.

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +        /* In this case the light of power at the X and Y coordinates are greater than Thor's initial condition so 2 if condition statements have to be implemented. Thor's initial X and Y conditions
Why does `(light_y > initial_ty) && (light_x > initial_tx)` means move SE? Why not NW or W or something else? Explain.

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +        /* Based on the compass it can be determined that Thor will travel E (East).The light_x is the position of the light of power  and initial_tx is Thor's starting position in the X-coordinate p
Why is `initial_tx` not updated? The same question applies for the rest of your if statements.

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +        /* Based on the compass it can be determined that Thor will travel E (East).The light_x is the position of the light of power  and initial_tx is Thor's starting position in the X-coordinate p
Why does `light_x > initial_tx` mean move east?

2022-03-04 14:58 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +        /* In this instance the light of power is in the negative Y direction of Thor's position. It is also at an angle which means Thor must move in an diagonal direction so that he does not run ou
Why only increment one variable? Why only test on variable for a diagonal move?

2022-03-08 00:02 UTC, bjones1 commented
I haven't seen any progress on this. Message me after you push update and are ready for another review.

2022-03-08 14:46 UTC, Kahjax commented
Ready for final changes review

2022-03-08 21:19 UTC, bjones1 requested changes

2022-03-08 21:19 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +.. image:: XYgraph.jpg
Starting here, indent your comments so they align with your code below.

2022-03-08 21:19 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +/* Based on the compass it can be determined that Thor will travel E (East).The light_x is the position of the light of power  and initial_thor_x is Thor's starting position in the X-coordinate plane
Indent (here and following) to align with code.

2022-03-08 21:19 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +            initial_thor_y++;
Why does x not change here?

2022-03-08 21:19 UTC, bjones1 commented on KJ1124/Thor_Puzzle_assign.c
> +// **ending bracket**
What about the other directions (NW, S, etc)?

2022-03-10 19:41 UTC, bjones1 commented
These comments still need to be addressed...

2022-03-24 21:59 UTC, bjones1 commented
Ping...still waiting on this...

2022-03-24 23:10 UTC, Kahjax commented
Dr. Jones,

I haven’t pushed the changes I made because I have not had good service on my computer on the trip. I will make these changes as a soon as I can.

Thanks in advance!

Kaitlyn Jackson
Electrical Engineering
Mississippi State University
(228)990-455
________________________________
From: Bryan A. Jones ***@***.***>
Sent: Thursday, March 24, 2022 2:59:26 PM
To: LiterateProgramming/exploring-github ***@***.***>
Cc: Jackson, Kaitlyn ***@***.***>; Author ***@***.***>
Subject: Re: [LiterateProgramming/exploring-github] Final Changes with Dr. J notes (PR #22)


Ping...still waiting on this...

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Njy_meZLG6M1cA38xccK2b8IKADeZqqbmirrasUtMuf08OdLcVDVlEE-ZovcoPB93Ar1tzCvizjRdbZEGy3_uSxfCEc52OM52kIoVXvdyexvueCm2zRcwUbELEqm22a6kTMR2xerVDOgqMnMJB1n2zMmGfSQcGKpAw5L0bKvXU83ZiIQBqzrEsd7ug3nyomoemKHFSaCXASsn2O0STKz6ax1k6RgO5IOijmVWxlPqvxKN-Z40VzqFh-r-m-Ue7yROyVXh4tRxQgc0pTEKWpftjO6ZQE8lFJeFRSZCsLduViIuA4sk0q0bYvrIL4gs5nw/https%3A%2F%2Fgithub.com%2FLiterateProgramming%2Fexploring-github%2Fpull%2F22%23issuecomment-1078423018>, or unsubscribe<https://secure-web.cisco.com/1wHjBVMwj5hlIucdDHJSQAqFWzx3XKTVC6UFHawlnSeijUFW02SkygP7biCleWbFXKbzs5fy00PQ0Jctp-FkcN_jyq6xmZipNTxctE4WHc5vPFu50cOkMtKlSpATpLSm6LYciFkBkidkmDdVREM0ZceGYsftMa6ZY9P_-vpKHrB_zdvw2w8SIYSm1BHQ_hj1r15u1AtBx7ISA1UKi8gyg1Q_Dl11R4ChM9gKdpZ0ZwKU8COnFCfXLvRyciCzodzm6wTG9szVZy6Dz2wirCjhtWoqGjRQTwb65GDgMT7GETUhYJT7CDOQx1CR78qBJJ1td/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX2DPAJPRN27BFNSWM75W43VBTQT5ANCNFSM5P4WNHQA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-25 16:13 UTC, bjones1 commented
I look forward to your updates. Comment here after you push so I know that you're ready for review.

2022-03-29 22:17 UTC, Kahjax commented
I made the necessary changes I forgot to comment here. Let me know if you cant see it

2022-04-05 12:43 UTC, bjones1 commented
I can't see any new commits.

2022-04-20 15:45 UTC, merged