Removing extra spaces
LiterateProgramming/exploring-github pull request #26
Opened 2022-03-08 00:42 UTC by Starnol

and trying to add the files we went over Friday

2022-03-08 14:12 UTC, Starnol commented
ready for review.

2022-03-08 21:31 UTC, bjones1 commented
Should I review this PR, or the other ones you opened? Close everything that's old so I know what to look at.

2022-03-10 14:36 UTC, Starnol commented
I have closed the other ones. And left comments. Alot of your comments were about the given code of the game. I am new to python so I can't really explain their given code. I had two thought processes during my second try with the game.  You originally asked for our thought processes. You are seeing inside my head.

2022-03-10 15:55 UTC, bjones1 requested changes

2022-03-10 15:55 UTC, bjones1 commented on OMC56/Thor Method.py
> +from re import X
I don't think you use this -- remove it if it's not used.

2022-03-10 15:55 UTC, bjones1 commented on OMC56/Thor Method.py
> + # **Light_x**: the X position of the light of power
Format as bulleted list or definition list:

```
#   :Light_x: the X position of the light of power
#   :Light_y: the Y position of the light of power
```

2022-03-10 15:55 UTC, bjones1 commented on OMC56/Thor Method.py
> +    remaining_turns = int(input())  # The remaining amount of turns Thor can move. Do not remove this line.
Put the comment on the previous line so CodeChat can render it.

2022-03-10 19:46 UTC, bjones1 requested changes

2022-03-10 19:46 UTC, bjones1 commented on OMC56/Thor Method_w_JP_comments.py
> +# ************************
Combine comments from JP so there's just one `Thor method.py` file will all improvements made to it. Delete this file.

2022-03-18 23:13 UTC, bjones1 commented
Liv, you need to address the comments I've left here before your homework assignment is complete.

2022-03-22 13:45 UTC, Starnol commented
I will work on this after work today. I want to get this cleaned up now that I believe I understand how smart git works. I would also like to set up a time to talk about how the framework looks for the microprocessor ebook. That would be a good guideline to work with. I have two Zeros with github. I was able to get the pull request for the first one to work. I will be trying to merge the files/commits this evening.

Very Respectfully,
Olivia Starnes
________________________________
From: Bryan A. Jones ***@***.***>
Sent: Friday, March 18, 2022 6:14 PM
To: LiterateProgramming/exploring-github ***@***.***>
Cc: Starnes, Liv ***@***.***>; Author ***@***.***>
Subject: Re: [LiterateProgramming/exploring-github] Removing extra spaces (PR #26)


Liv, you need to address the comments I've left here before your homework assignment is complete.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1OoesP8gO74kB7HH-H4aQR0MAuWAgV6uOOyCLXgFLDXx3MzgBUmf_zaHftDMeRJc1FKMdObySWyVSrYC8N4mIcbG_m_TNYqg6jdp8hPDYlPkp4zcSzck4B55loVwGkDRPNYO2wJ7i0b8V5srbZA9Z9MIu6XX3oIXEOiWCgHp4yCTey_BqjALeOoa87bl-Pt62s_DYJj0ACqMoW2b0icPSD-Bea_SEj__Qt5DmzsT6aGJ-54dw3w4RugLCEaUAtLHFJH-Uh5JkoQbFj6DioapG05bbBNuT1ZJ0du_wO97mapWzAl8AWp5v_dNDMGJdGf88/https%3A%2F%2Fgithub.com%2FLiterateProgramming%2Fexploring-github%2Fpull%2F26%23issuecomment-1072880809>, or unsubscribe<https://secure-web.cisco.com/1-1HNAMR7oYG7A8q8fGLIMEgcdsiK-EUBhRpc5ythAIAoaxRAIfBhz4elGOy90BnNyM_WeM1pqp_oCGrnQKqqRwHcIWs3aX1r2PB5IRqTHo1std0ettmSliTalkDF2OVtCEqneRmc9KPgNWCu8oLimpyQCzpp3bQpRbOsYWxiGe396Wfnzn6w28sKka1J0hEkjl2DeQhp0u6Oe5bXmtoBLGmOiGdlG8-_2MCrUIT61iuzBA4T-bs7uYfzUwI-5y2qwk-Dw11MGh9F2ApDdQSDBbwsSDlLTDSo80oyeM42-Nck1q5fZlZf2uxjmWk7hoQY/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX2DNLPCLHQ753YN42YNGF3VAUE4FANCNFSM5QE32T7Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://secure-web.cisco.com/1-crGB-kf9ti4nPWyvJYCFRfgPHFi0W9r2HJ6aUxHsLYUjAFpAGcD7fzoAp4z0wih2T8bjLHIqaHtViHvExCy2jr0Sd-tZddQT21HZJNsZ41JJMjSIbB1sQSGTn-iE0_QG2DHOEXVFEHJpEtRKEs9MdxFVrB4PpOdXOa7rrzhZx7rj_BT0c4bYWhTpGAta6Af5HlFh2j9agWfZdBdIoh9h6XONGU8sd7uOUzeF7SRXAJIdTJ5rfsSE3YRu1akfhLNVx8xxWKGyDZ8KBmME4MjNSe3KTI0SZ6M65Yu9ChN5O04m8v5DFAyfXbhXS8zg42z/https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://secure-web.cisco.com/12bssnjmyBykq3zrwNKTAyBf3Ql5SvUqboJYZWL9xY5hjYiNOd34xFx0axRXyJ9n-_7PlsIXvmAkrds3OASdxyZcZPDW6cRs7GBdi8CGtbAx838_1xSvw-3H1FfBgrzGdAJX677bSnNPZIefXRpVuZQyj27rXy1XPnOheKC9wi8dsXRxZv9NNYgLvyfUf7W4TzL2xMear1CxwGhDovuZx6I6vdcCqpiVYKyq0ie0uvHyNUB3YSe2cDVbhJ-Mv2qTlQArza3rJpymjFK2xRuCjxBGKIkjouwv5QM1CjQ9r267Cf1KG0lvhSgiXL8G_h4R1/https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-22 14:41 UTC, bjones1 commented
I look forward to seeing your progress! Kaitlyn scheduled a meeting today at 4:00 PM about the e-book. I've also created a channel in the class MS Teams account for the e-book and discussion on it.

2022-03-24 21:59 UTC, bjones1 commented
Ping...still waiting on this...

2022-03-25 02:16 UTC, Starnol commented
My smart git is longer working. It keeps saying I need a License.
________________________________
From: Bryan A. Jones ***@***.***>
Sent: Thursday, March 24, 2022 4:59 PM
To: LiterateProgramming/exploring-github ***@***.***>
Cc: Starnes, Liv ***@***.***>; Author ***@***.***>
Subject: Re: [LiterateProgramming/exploring-github] Removing extra spaces (PR #26)


Ping...still waiting on this...

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1UXXEwV_zkT9cL3D6BQPn2TPuVktQANxm5LuarJsnPE2YKaNiPsKptwcFAhypkBA2d0Iz1W_W9-feUBP54PkLhUzKAS6TDpwdZFthrZxh1ioGitJDLfPwlyyBpotkus_t3JslF1idB6cCWvHrTGmUgeptg4paVQzEI2c5PPSWV1f-Dwxsedm5UJrBFNSnnIb2BsLUW7Ppz5j9MdrAegfFn3DBfaGel-5AYUhZj1g33i3A9NBIWkJmZd3twiTPVEa8UH-ozF-3y82PfbWqAWs8tbGP_ZNwUQYsNj5rHidEfS-UvkKCerRIj1AlUhMhDO_A/https%3A%2F%2Fgithub.com%2FLiterateProgramming%2Fexploring-github%2Fpull%2F26%23issuecomment-1078422861>, or unsubscribe<https://secure-web.cisco.com/1FaJvChC87ZKAy7RmrVRxWMRXFm49ptI97haMwHxD2l88jTDrDAbekAa_4Mh7PBCUEFBUG79ZqyIencLiSpbSI5tThLWUSyF4fA-TVSRCoGtgP-EVy4ROjfJ3ZlbXeJO-kYrx89eixNnwQpjciCJP2hAX5GoVpxPsQUTk0EHisiqmbRvhB_wZBTcDPMolTSe5215vactB0e9GKgtHWoLbhZAcxYdOPScDEI6TJ3-R46H53hjdEjg770S1OT3IOsUYJ9frX2E_Js2z3SlDmabkEqXABu4Gi0D5k_C6b9baKKwB044Z4HyKKQaFnjbowYDy/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX2DNLN7CUR7H7KQY52NXB3VBTQS5ANCNFSM5QE32T7Q>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-25 03:08 UTC, bjones1 commented
You may have signed up for a commercial license with a 30-day trial. Check the smartgit website or reinstall to fix. Pick the free / open source license.

2022-03-27 01:29 UTC, closed without merging