Intro to GitHub Part 1
LiterateProgramming/exploring-github pull request #27
Opened 2022-03-08 14:43 UTC by jpg323

First updated pull request

2022-03-08 21:32 UTC, bjones1 commented on jpg323(ShadowsOfTheKnight)/gameCode.py
> +# ***************************
Put your name in the title so that everyone will know who wrote this.

2022-03-08 21:36 UTC, bjones1 requested changes

2022-03-08 21:36 UTC, bjones1 commented on jpg323(ShadowsOfTheKnight)/gameCode.py
> +# Approach
Add a blank line before this to keep the code more readable.

2022-03-08 21:36 UTC, bjones1 commented on jpg323(ShadowsOfTheKnight)/gameCode.py
> +# | The approach we are taking is based on a binary search tree. We will check what *directions* are in the **bomb_dir** string and write if-statements for each case.
Don't use a line block (`# | The approach...`); instead, use `# The approach...`.

2022-03-08 21:36 UTC, bjones1 commented on jpg323(ShadowsOfTheKnight)/gameCode.py
> +# |
Omit line blocks.

2022-03-08 21:36 UTC, bjones1 commented on jpg323(ShadowsOfTheKnight)/gameCode.py
> +    # **VERTICAL**
This renders poorly -- either start a new paragraph or make these a line block.

2022-03-10 19:42 UTC, bjones1 commented
These comments still need to be addressed...

2022-03-24 21:58 UTC, bjones1 commented
Ping...

2022-03-29 03:30 UTC, jpg323 reviewed
It looks like I never pushed these changes, it should be resolved now.

2022-03-29 12:41 UTC, bjones1 commented
You still didn't push anything new to this branch.

2022-04-20 15:49 UTC, merged