Added testing three times
LiterateProgramming/exploring-github pull request #4
Opened 2022-02-22 15:09 UTC by scarbroughzach

2022-03-02 21:00 UTC, bjones1 commented
Zach,

Thanks! This is a good first submission. Next, you need to:

- Put all your files in a subdirectory named `zws40`.
- Look at comments I've left on each file.

This is due by 12PM tomorrow (3-Mar).

2022-03-02 21:02 UTC, bjones1 requested changes

2022-03-02 21:02 UTC, bjones1 commented on Intro_to_CodeChat With comments.c
> +
Combine this file with `Intro_to_CodeChat.c`, then delete this file.

2022-03-02 21:02 UTC, bjones1 commented on Intro_to_CodeChat_orig.c
> +
Same -- combine with `Intro_to_CodeChat.c`, then delete.

2022-03-02 21:02 UTC, bjones1 commented on welcome.rst
> +This is an upstream change.
Delete this file.

2022-03-02 21:02 UTC, bjones1 commented on zws40/TheDescentReview.py
> +# The Descent
Delete this file.

2022-03-02 21:03 UTC, bjones1 commented
Delete all the .zip files and all images for Austin's program.

2022-03-07 23:57 UTC, bjones1 commented
Combine all three source files, so you have a single source file with improvements from both me and Austin in it. Leave a message here when that's done.

2022-03-08 14:53 UTC, scarbroughzach commented
Fixed, please review

2022-03-08 16:45 UTC, bjones1 requested changes

2022-03-08 16:45 UTC, bjones1 commented on welcome.rst
> +This is an upstream change.
Still need to delete this file...

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +
Put `//` comments to connect these lines, to avoid unnecessary space between paragraphs.

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +
Same -- need `//` here and between following paragraphs.

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +    // X coordinate of a surface point. (0 to 6999)
Indent this comment, since it belongs to the code below it. Also remove the blank line so comment and code are clearly connected.

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +    // the horizontal speed (in m/s), can be negative.
Indent comments and code so they align.

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +// The solution begins with an if else statement that looks at the Y altitude. If the landers is more than 1250 meters, it was retain a speed of -25 m/s as to not gain too much speed and lose control
I don't understand this sentence -- "it was retain a speed"? Revise.

2022-03-08 16:45 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +// The solution begins with an if else statement that looks at the Y altitude. If the landers is more than 1250 meters, it was retain a speed of -25 m/s as to not gain too much speed and lose control
Indent comments to match code.

2022-03-10 19:57 UTC, bjones1 commented
Still waiting on these changes...

2022-03-23 18:26 UTC, bjones1 requested changes

2022-03-23 18:26 UTC, bjones1 commented on welcome.rst
> +Welcome!
Still needs to be deleted.

2022-03-23 18:26 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +
Delete this line, so that the comment and the variable are next to each other.

2022-03-23 18:26 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +//
Indent to align with comments above/below.

2022-03-23 18:26 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +     // You use the printf function to choose your thruster strength on a level 0-4. The first number, or the zero you see, of the function can be ignored, while the second number is your thrust powe
Align with printf.

2022-03-23 18:26 UTC, bjones1 commented on zws40/Intro_to_CodeChat.c
> +     // Once below 1250 meters, the else condition is set to run. This is because at this distance you need to begin slowing down as to not crash onto the ground.
Align with else

2022-03-24 14:20 UTC, scarbroughzach commented
Please review

2022-03-24 21:46 UTC, merged